[2022-07-29T12:08:21] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IHDR' 16 13
[2022-07-29T12:08:21] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'sRGB' 41 1
[2022-07-29T12:08:21] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IDAT' 54 8192
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing BlpImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing BmpImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing BufrStubImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing CurImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing DcxImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing DdsImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing EpsImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing FitsImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing FitsStubImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing FliImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing FpxImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:404] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing FtexImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing GbrImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing GifImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing GribStubImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing Hdf5StubImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing IcnsImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing IcoImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing ImImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing ImtImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing IptcImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing JpegImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing Jpeg2KImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing McIdasImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing MicImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:404] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing MpegImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing MpoImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing MspImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PalmImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PcdImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PcxImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PdfImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PixarImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PngImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PpmImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing PsdImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing SgiImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing SpiderImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing SunImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing TgaImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing TiffImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing WebPImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing WmfImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing XbmImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing XpmImagePlugin
[2022-07-29T12:08:21] DEBUG [PIL.Image.init:401] Importing XVThumbImagePlugin
[2022-07-29T12:10:31] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\apps\models.py changed, reloading.
[2022-07-29T12:11:45] INFO [root.logout:188] admin_ logged out
[2022-07-29T12:11:48] INFO [root.logout:188] _ logged out
[2022-07-29T12:11:50] INFO [root.showapps:43] admin_seen the whole applist
[2022-07-29T12:11:51] ERROR [django.request.log_response:224] Internal Server Error: /apps/all/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'ImageFieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\saketh\Downloads\billapp\apps\views.py", line 44, in showapps
    return render(request,'showapps.html',{'showapp':appli,'leni':leni,'msg':mssg})
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\files.py", line 63, in url
    self._require_file()
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\fields\files.py", line 40, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'appimg' attribute has no file associated with it.
[2022-07-29T12:12:29] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IHDR' 16 13
[2022-07-29T12:12:29] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'sRGB' 41 1
[2022-07-29T12:12:29] DEBUG [PIL.PngImagePlugin.call:213] STREAM b'IDAT' 54 8192
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing BlpImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing BmpImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing BufrStubImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing CurImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing DcxImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing DdsImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing EpsImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing FitsImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing FitsStubImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing FliImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing FpxImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:404] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing FtexImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing GbrImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing GifImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing GribStubImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing Hdf5StubImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing IcnsImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing IcoImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing ImImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing ImtImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing IptcImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing JpegImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing Jpeg2KImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing McIdasImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing MicImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:404] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing MpegImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing MpoImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing MspImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PalmImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PcdImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PcxImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PdfImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PixarImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PngImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PpmImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing PsdImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing SgiImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing SpiderImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing SunImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing TgaImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing TiffImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing WebPImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing WmfImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing XbmImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing XpmImagePlugin
[2022-07-29T12:12:29] DEBUG [PIL.Image.init:401] Importing XVThumbImagePlugin
[2022-07-29T12:12:34] INFO [root.showapps:43] admin_seen the whole applist
[2022-07-29T12:12:37] INFO [root.showapps:43] admin_seen the whole applist
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/css/styles.css
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/illustrations/rocket-white.png
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-xd.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-3.jpg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-2.jpg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-4.jpg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-atlassian.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-spotify.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-slack.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-invision.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/small-logos/logo-jira.svg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/chartjs.min.js
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-07-29T12:12:39] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/img/team-1.jpg
[2022-07-29T12:12:44] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/estimate.html
[2022-07-29T12:12:45] WARNING [django.request.log_response:224] Not Found: /apps/instagram/dashboard/assets/js/plugins/perfect-scrollbar.min.js
[2022-07-29T12:14:36] WARNING [django.request.log_response:224] Not Found: /admin/instagram
[2022-07-29T12:15:45] WARNING [django.request.log_response:224] Not Found: /favicon.ico
[2022-07-29T12:16:09] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:19:14] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:29:20] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\views.py changed, reloading.
[2022-07-29T12:29:27] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:30:18] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:32:42] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:33:41] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:35:42] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:36:10] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:36:29] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:37:51] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:38:14] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:38:48] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:38:54] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:38:55] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:40:20] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:40:42] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:41:08] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:41:25] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\models.py changed, reloading.
[2022-07-29T12:42:02] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:42:12] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:43:56] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:44:24] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\models.py changed, reloading.
[2022-07-29T12:45:04] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\models.py changed, reloading.
[2022-07-29T12:45:27] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\models.py changed, reloading.
[2022-07-29T12:53:59] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:55:44] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:55:52] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T12:59:55] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\models.py changed, reloading.
[2022-07-29T13:01:41] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:02:12] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:03:21] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:03:36] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:04:05] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:04:22] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:05:19] ERROR [django.request.log_response:224] Internal Server Error: /update-profile-save/ruchitha/instagram
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view accounts.views.update_profile_save didn't return an HttpResponse object. It returned None instead.
[2022-07-29T13:08:49] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\forms.py changed, reloading.
[2022-07-29T13:08:59] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\forms.py changed, reloading.
[2022-07-29T13:09:01] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\forms.py changed, reloading.
[2022-07-29T13:09:03] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\forms.py changed, reloading.
[2022-07-29T13:09:07] INFO [django.utils.autoreload.trigger_reload:251] C:\Users\saketh\Downloads\billapp\accounts\forms.py changed, reloading.
[2022-07-29T13:09:30] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:09:40] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:09:52] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:09:54] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:09:55] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:09:55] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:10:30] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:10:31] ERROR [django.request.log_response:224] Internal Server Error: /apps/create.html/add-customer-form/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\dashboard\views.py", line 206, in add_customer_form
    app = applists.objects.get(slug=slug)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.models.applists.DoesNotExist: applists matching query does not exist.
[2022-07-29T13:11:15] ERROR [django.request.log_response:224] Internal Server Error: /apps/create.html/add-customer-form/
Traceback (most recent call last):
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\saketh\Downloads\billapp\dashboard\views.py", line 206, in add_customer_form
    app = applists.objects.get(slug=slug)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\saketh\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.models.applists.DoesNotExist: applists matching query does not exist.
[2022-07-29T13:11:20] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:11:28] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:11:28] WARNING [django.request.log_response:224] Not Found: /ruchitha/js/create.js
[2022-07-29T13:16:09] WARNING [django.request.log_response:224] Not Found: /apps/instagram/add-customer-form/create.html
